// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3YG1OO9Ko4J8ojF4YNWRoDLt8Bba36yQ',
    appId: '1:866414021316:web:4d7bc6acfa336e58729791',
    messagingSenderId: '866414021316',
    projectId: 'todo-app-b3481',
    authDomain: 'todo-app-b3481.firebaseapp.com',
    storageBucket: 'todo-app-b3481.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmwQf8UnAI9a0lW3cD0VvyMu77POqmsoQ',
    appId: '1:866414021316:android:d85e308bc29c7b01729791',
    messagingSenderId: '866414021316',
    projectId: 'todo-app-b3481',
    storageBucket: 'todo-app-b3481.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiDA1Go6yUScZgiFkCYOpNB0c30oN27AI',
    appId: '1:866414021316:ios:290c48e2eee3b8bb729791',
    messagingSenderId: '866414021316',
    projectId: 'todo-app-b3481',
    storageBucket: 'todo-app-b3481.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiDA1Go6yUScZgiFkCYOpNB0c30oN27AI',
    appId: '1:866414021316:ios:290c48e2eee3b8bb729791',
    messagingSenderId: '866414021316',
    projectId: 'todo-app-b3481',
    storageBucket: 'todo-app-b3481.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3YG1OO9Ko4J8ojF4YNWRoDLt8Bba36yQ',
    appId: '1:866414021316:web:0b13b91d1a27506c729791',
    messagingSenderId: '866414021316',
    projectId: 'todo-app-b3481',
    authDomain: 'todo-app-b3481.firebaseapp.com',
    storageBucket: 'todo-app-b3481.firebasestorage.app',
  );
}
